# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 15:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_vat_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isInteger',
            field=models.BooleanField(default=True, verbose_name='integer quantity'),
        ),
    ]
